#Q1. what is the total revenue generated by male vs female customers?

SELECT 
    gender, SUM(purchase_amount)
FROM
    customer
GROUP BY gender;

#Q2. which customers used a discount but still spend more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

#Q3. which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Q4. compare the average purchase amount between standard and express shipping.

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

#Q5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue desc, avg_spend DESC;

#Q6. which 5 products have the highest percentage  of purchase with discounts applied?

SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Q7. segment customers into new, returning , and loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as( select customer_id , previous_purchases, case when previous_purchases = 1 then 'new' 
when previous_purchases between 2 and 10 then ' returning' 
else 'loyal' end as customer_segment from customer)
select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment;

#Q8. what are the top 3 most purchased products within each category?

with item_counts as (select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank from customer
group by category, item_purchased)
select item_rank, category , item_purchased, total_orders
from item_counts
where item_rank<=3;

#Q9. are customers who are repeat buyers ( more then 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

#Q10. what is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;

#Q11. which payment method is most popular among loyal customers vs new customers?

with customer_type as (
select customer_id , payment_method ,
case when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as segment
from customer)
select segment, payment_method, count(*) as total
from customer_type
group by segment, payment_method
order by segment , total desc;

#Q12. Which season drives the most revenue and which category performs best in each season?

select season , category, sum(purchase_amount) as revenue,
rank() over(partition by season order by sum(purchase_amount) desc) as category_rank
from customer 
group by season , category;

#Q13. What is the average review rating for discounted vs non-discounted purchases?

select discount_applied, round(avg(review_rating),2) as avg_rating,
count(*) as total_purchases
from customer group by discount_applied;



